import type { Patient } from "./types"

export const mockPatients: Patient[] = [
  {
    id: 1,
    name: "Sarah Johnson",
    age: 34,
    email: "sarah.johnson@email.com",
    phone: "+1 (555) 123-4567",
    address: "123 Main St, New York, NY 10001",
    medicalHistory: ["Hypertension", "Diabetes Type 2"],
    lastVisit: "2024-01-15",
    nextAppointment: "2024-02-15",
    status: "active",
    bloodType: "A+",
    allergies: ["Penicillin", "Shellfish"],
    emergencyContact: {
      name: "John Johnson",
      phone: "+1 (555) 123-4568",
      relationship: "Spouse",
    },
  },
  {
    id: 2,
    name: "Michael Chen",
    age: 45,
    email: "michael.chen@email.com",
    phone: "+1 (555) 234-5678",
    address: "456 Oak Ave, Los Angeles, CA 90210",
    medicalHistory: ["Asthma", "High Cholesterol"],
    lastVisit: "2024-01-20",
    nextAppointment: "2024-02-20",
    status: "active",
    bloodType: "B-",
    allergies: ["Latex"],
    emergencyContact: {
      name: "Lisa Chen",
      phone: "+1 (555) 234-5679",
      relationship: "Wife",
    },
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    age: 28,
    email: "emily.rodriguez@email.com",
    phone: "+1 (555) 345-6789",
    address: "789 Pine St, Chicago, IL 60601",
    medicalHistory: ["Migraine", "Anxiety"],
    lastVisit: "2024-01-10",
    status: "active",
    bloodType: "O+",
    allergies: [],
    emergencyContact: {
      name: "Carlos Rodriguez",
      phone: "+1 (555) 345-6790",
      relationship: "Brother",
    },
  },
  {
    id: 4,
    name: "David Wilson",
    age: 67,
    email: "david.wilson@email.com",
    phone: "+1 (555) 456-7890",
    address: "321 Elm St, Houston, TX 77001",
    medicalHistory: ["Heart Disease", "Arthritis", "Hypertension"],
    lastVisit: "2024-01-25",
    nextAppointment: "2024-02-10",
    status: "critical",
    bloodType: "AB+",
    allergies: ["Aspirin"],
    emergencyContact: {
      name: "Margaret Wilson",
      phone: "+1 (555) 456-7891",
      relationship: "Wife",
    },
  },
  {
    id: 5,
    name: "Jessica Brown",
    age: 31,
    email: "jessica.brown@email.com",
    phone: "+1 (555) 567-8901",
    address: "654 Maple Dr, Phoenix, AZ 85001",
    medicalHistory: ["Thyroid Disorder"],
    lastVisit: "2024-01-18",
    nextAppointment: "2024-03-01",
    status: "active",
    bloodType: "A-",
    allergies: ["Iodine"],
    emergencyContact: {
      name: "Robert Brown",
      phone: "+1 (555) 567-8902",
      relationship: "Husband",
    },
  },
  {
    id: 6,
    name: "Robert Taylor",
    age: 52,
    email: "robert.taylor@email.com",
    phone: "+1 (555) 678-9012",
    address: "987 Cedar Ln, Philadelphia, PA 19101",
    medicalHistory: ["Back Pain", "Sleep Apnea"],
    lastVisit: "2024-01-12",
    status: "inactive",
    bloodType: "O-",
    allergies: [],
    emergencyContact: {
      name: "Susan Taylor",
      phone: "+1 (555) 678-9013",
      relationship: "Wife",
    },
  },
  {
    id: 7,
    name: "Amanda Davis",
    age: 39,
    email: "amanda.davis@email.com",
    phone: "+1 (555) 789-0123",
    address: "147 Birch St, San Antonio, TX 78201",
    medicalHistory: ["Depression", "Fibromyalgia"],
    lastVisit: "2024-01-22",
    nextAppointment: "2024-02-25",
    status: "active",
    bloodType: "B+",
    allergies: ["Codeine"],
    emergencyContact: {
      name: "Mark Davis",
      phone: "+1 (555) 789-0124",
      relationship: "Husband",
    },
  },
  {
    id: 8,
    name: "Christopher Miller",
    age: 41,
    email: "chris.miller@email.com",
    phone: "+1 (555) 890-1234",
    address: "258 Spruce Ave, San Diego, CA 92101",
    medicalHistory: ["Kidney Stones", "Gout"],
    lastVisit: "2024-01-08",
    nextAppointment: "2024-02-12",
    status: "active",
    bloodType: "A+",
    allergies: ["Sulfa drugs"],
    emergencyContact: {
      name: "Jennifer Miller",
      phone: "+1 (555) 890-1235",
      relationship: "Wife",
    },
  },
]
